series: Basic OpenGL with GLFW
title: Geometry Shaders
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use Geometry Shaders to procedurally render geometry with very little initial vertex data.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: Fragment Shaders